name: flutter_pokedex
description: "Flutter Pokèdex"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.3
  mime: ^1.0.5
  dio: ^5.5.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  hive: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_background_service: ^5.0.6
  flutter_markdown: ^0.7.3
  camera: ^0.11.0+1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
